# Generated by Django 4.0.2 on 2022-04-09 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_account_id_alter_tasks_id_alter_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodorout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(verbose_name='TTT')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_Title',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task_imrating',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignments',
            field=models.CharField(default=-1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_dates',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 0, 50, 2, 550179, tzinfo=utc), verbose_name='TTT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='importance_raiting',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
