# Generated by Django 4.0.2 on 2022-04-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignments',
            new_name='Title',
        ),
    ]
