# Generated by Django 4.0.2 on 2022-04-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_rename_assignments_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_dates',
            field=models.DateTimeField(null=True),
        ),
    ]
