# Generated by Django 4.0.2 on 2022-04-21 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0008_rename_title_task_title_alter_task_due_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodorout',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pomodorout',
            name='start_date',
        ),
        migrations.AddField(
            model_name='pomodorout',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorout',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodorout',
            name='times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomodorout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
